{{
  exports.publishOn = new Date().toString();
}}

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer

{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nestjs-5",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImagUrl": "http://localhost.com/images/image1.jpg",
  "metaOptions" : {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
    },
  "tags": [1,2]
}