PATCH http://localhost:3000/posts
Content-Type: application/json
{
  "id": 1,
  "title": "Second Post",
  "postType": "story",
  "slug": "second-post",
  "status": "draft",
  "content": "This is my second posts",
  "schema":  "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
  "featuredImagUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-03-16T07:46:32+0000"
}