POST http:localhost:3000/users
Content-Type: application/json
{
  "firstname": "Mark",
  "lastname": "Melly",
  "email": "Melly@mail.com",
  "password": "Test123$"
}

POST http:localhost:3000/users/create-many
Content-Type: application/json
{
  "users": [
  {
    "firstname": "gregy",
    "lastname": "whoy",
    "email": "gregy@mail.com",
    "password": 
  },
  {
    "firstname": "Alexy",
    "lastname": "Conney",
    "email": "Alexy@mail.com",
    "password": 
  }
  ]
}