POST http://localhost:3000/tags
Content-Type: application/json
{
  "name": "Grid System-CSS",
  "slug": "grid-system-css",
  "description": "This is a description for tpescript tag",
  "schema": "{\"DarkThemeEnabled\": false, \"footerActive\": true}",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg"
}